#!/usr/bin/env python

import argparse
import socket

parser = argparse.ArgumentParser()
parser.add_argument("-t", "--type", help="Type de commande vocale")
parser.add_argument("-d", "--data", help="Nombre de fois qu'on execute la commande (cela simule le nombre de metres)")

args = parser.parse_args()

type = args.type
data = args.data

if type != "":
	s = socket.socket()         
	 
	s.bind(('192.168.4.1', 65535))
	s.listen(0)
	client, addr = s.accept()
	i = 0
	
	if type == "movement/forward":
		
		client.send("coucou de la raspberry")
		
		print(data)
		
		while i != data:
		
			#On envoi un byte de 80 car c'est celui du forward
			client.send(80)
			i = i+1
			sleep(100)
			print("ici")
			
	if type == "movement/backward":
		
		 while i != data:
		 
				#Byte du backward
				client.send(82)
				i = i+1
				
	#Partie reception des donnees de l'arduino
	'''
	while True:
		content = client.recv(32)
 
		if len(content) == 0:
		   break
 
		else:
			print(content)
			'''			
	print("Closing connection")
	client.close()
	i = 0
